services:

  apache_php_proyecto:

    build:
      context: .docker
      dockerfile: Dockerfile
    container_name: php_apache

    volumes:
      - ./src/:/var/www/html
      - .docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - .docker/php/php.ini:/usr/local/etc/php/php.ini-development
      #- .docker/xdebug/debug.ini:/usr/local/bin/php/conf.d/debug.ini

    expose:
      - 80
    ports:
      - 8080:80
    networks:
      - proyecto1
    links:
      - mariadb
      - mongo
    extra_hosts:
      - "host.docker.internal:host-gateway"


  mariadb:
    image: mariadb:latest
    restart: on-failure

    volumes:
      - .docker/mariadb:/var/lib/mysql:z

    ports:
      - 3306:3306

    networks:
      - proyecto1

    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: proyecto
      MARIADB_USER: javier
      MARIADB_PASSWORD: 3434

    command:
      --default-authentication-plugin=mysql_native_password

  mongo:
    image: mongo:latest
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    networks:
      - proyecto1


networks:
  proyecto1:
    name: proyecto1
    driver: bridge